Start implementing the model editor.

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -167,6 +167,19 @@ cosy_temp=$(realpath "${cosy_temp}")
   export LD_LIBRARY_PATH="${cosy_prefix}/lib:${LD_LIBRARY_PATH}"
 }
 
+# Install libev:
+{
+  export CC=clang
+  echo -n "Installing libev... "
+  ( cd dependencies/libev || exit 1
+    ./configure --prefix="${cosy_prefix}"
+    make
+    ${sudo} make install
+  ) >> "${cosy_log}" 2>&1 \
+    && echo -e "${green}success${nc}" \
+    || echo -e "${red}failure${nc}"
+}
+
 # Install lua, luarocks and packages:
 {
   export CC=clang
@@ -278,6 +291,15 @@ echo -n "Installing openresty... "
     fi
   done
 ) >> "${cosy_log}" 2>&1 \
+  && echo -e "${green}success${nc}" \
+  || echo -e "${red}failure${nc}"
+
+
+# Patch lapis:
+echo -n "Patching lapis request... "
+{
+  patch -i patch-request.txt "${cosy_prefix}/share/lua/5.1/lapis/spec/request.lua"
+} >> "${cosy_log}" 2>&1 \
   && echo -e "${green}success${nc}" \
   || echo -e "${red}failure${nc}"
 
