Add runner for editors.

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -142,7 +142,7 @@ cosy_temp=$(realpath "${cosy_temp}")
                                    perl build-essential wget python python-pip \
                                    libc6-dev libssl-dev \
                                    libreadline-dev libncurses5-dev libpcre3-dev \
-                                   npm libc-bin postgresql shellcheck
+                                   npm libc-bin redis postgresql shellcheck
         ;;
       "Darwin")
         HOMEBREW_PREFIX=$(brew config | grep "HOMEBREW_PREFIX" | tr -d ' \t' | cut -d ":" -f 2)
@@ -151,7 +151,7 @@ cosy_temp=$(realpath "${cosy_temp}")
         export LD_LIBRARY_PATH="${HOMEBREW_PREFIX}/lib:${LD_LIBRARY_PATH}"
         export DYLD_LIBRARY_PATH="${HOMEBREW_PREFIX}/lib:${DYLD_LIBRARY_PATH}"
         brew update
-        brew install openssl pcre python wget npm libcaca postgresql shellcheck
+        brew install openssl pcre python wget npm libcaca postgresql redis shellcheck
         brew link --force openssl
         ;;
       *)
@@ -197,6 +197,11 @@ cosy_temp=$(realpath "${cosy_temp}")
     || echo -e "${red}failure${nc}"
   echo -n "Installing lua-cjson-ol rock... "
   ${sudo} "${cosy_prefix}/bin/luarocks" install lua-cjson-ol \
+    >> "${cosy_log}" 2>&1 \
+    && echo -e "${green}success${nc}" \
+    || echo -e "${red}failure${nc}"
+  echo -n "Installing lapis-redis rock... "
+  ${sudo} "${cosy_prefix}/bin/luarocks" install --server=https://luarocks.org/dev lapis-redis \
     >> "${cosy_log}" 2>&1 \
     && echo -e "${green}success${nc}" \
     || echo -e "${red}failure${nc}"
